name: ens_lookup
description: Simple package for ENS lookup
version: 0.1.0
homepage: https://github.com/kayumarie/ens_lookup/actions

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  web3dart: ^2.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  http: ^0.13.5
