name: Run tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  init:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Dart'
        uses: dart-lang/setup-dart@v1

      - name: 'Run tests'
        run: |
          dart test
